### PR TITLE
Fixes to master branch

### PR DESCRIPTION
**Pull request by garrensmith**
This is just some fixes to the current master branch. 

* Make sure that Travis tests against node 8 and 9
* Remove the usage of babel. It would be nice to be able to use this lib with needing babel and since all the es6 features are supported in 8 and 9 and I don't think we would need it.
* Finally update the examples to work with the latest changes to raft.

I have made some opinionated changes to the code base - using fat arrows etc. If that isn't the style you want in this please let me know and I can change it.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Thanks for the changes, I agree, the need for babel was maybe a bit overkill. I'm fine with fat arrows, as long as they make sense when they are used.

**Comment by garrensmith** [comment]
Brillant. Thanks @3rd-Eden

**Comment by lpinca** [comment]
Wasn't babel needed to support old browsers?

**Comment by 3rd-Eden** [comment]
@lpinca Shit, your right.

**Comment by 3rd-Eden** [comment]
Added babel compilation back, but only for browsers. Added dedicated `browser` directive that points to a babel build that will be made during `prepublish`.

**Pull request merged**
